#!/bin/sh -e

PECL_NAME=idn

# Source debconf library.
. /usr/share/debconf/confmodule

db_title "PHP"

for SAPI in apache apache2 cgi cli
do
	# Skip this loop if the config file isn't there (yet).
	if [ -f "/etc/php4/$SAPI/php.ini" ]; then
		db_register php4/add_extension php4/extension_${PECL_NAME}_$SAPI

		if grep -q "^[[:space:]]*extension[[:space:]]*=[[:space:]]*${PECL_NAME}.so" "/etc/php4/$SAPI/php.ini"
		then
			db_set php4/extension_${PECL_NAME}_$SAPI true
		else
			db_set php4/extension_${PECL_NAME}_$SAPI false
		fi

		db_subst php4/extension_${PECL_NAME}_$SAPI extname ${PECL_NAME}
		db_subst php4/extension_${PECL_NAME}_$SAPI sapiconfig $SAPI
		db_input low php4/extension_${PECL_NAME}_$SAPI || true
	fi
done

db_go
